server:
  port: 8808
  tomcat:
    uri-encording: UTF-8
    maxHttpHeaderSize: 10240000
    maxHttpPostSize: 10240000
  servlet:
    context-path: /
  
spring:
  application:
    name: water-admin
  devtools:
    livereload:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/down?useSSL=false&characterEncoding=UTF-8&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: 
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 200
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  servlet:
    multipart:
      #单个文件的大小
      max-file-size: 20MB
  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: true
    charset: UTF-8
    check-template-location: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    suffix: .html
    template-loader-path: classpath:/
    settings:
      template_update_delay: 0
      default_encoding: UTF-8
      classic_compatible: true
    order: 1
    request-context-attribute: rs
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
  #输出日志
logging:
  level:
    root: info
    com.water: debug    
#mybatis plus配置
mybatis-plus: 
  mapper-locations: classpath*:com/water/module/**/mapper/*.xml
  type-aliases-package: com.water.module.**.entity
  configuration:
  #默认情况下,Mybatis对Map的解析生成, 如果值(value)为null的话,那么key也不会被加入到map中
    call-setters-on-nulls: true
  global-config:
    db-config:
           #全局默认主键类型，设置为自增
      id-type: auto
           #逻辑已删除值,(逻辑删除下有效)
      logic-delete-value: 1
           #逻辑未删除值,(逻辑删除下有效)
      logic-not-delete-value: 0
management:
  endpoints:
    web:
      exposure:
        include: health